### PR TITLE
fix/#2

### PR DESCRIPTION
**Pull request by alistairsykes**
Changed the lib to declare the camera features as optional. Then changed the sample app to declare them as required. Also removed the uses-permission CAMERA from the sample app, as its already stated in the lib and does not need to be re-declared. An update has also been made to the wiki to reflect this change - see https://github.com/brightec/KBarcode/wiki/Reference#manifest

Fix for #2

---
This change is [Reviewable](https://reviewable.io/reviews/brightec/kbarcode/3)

### CODE REVIEW

**Comment by alistairsykes** [comment]
There is currently an incident in bintray which is stopping our ci checks from downloading dependencies and running.

https://status.bintray.com/incidents/2wvx6d5f807c

I have run these checks locally and they pass.

**Comment by alistairsykes** [comment]
Still passes locally after latest commit

**Review by NickHolcombe — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/brightec/kbarcode/3)* status: all files reviewed, 1 unresolved discussion (waiting on @alistairsykes)

___
*[app/src/main/AndroidManifest.xml, line 6 at r2](https://reviewable.io/reviews/brightec/kbarcode/3#-LaUqX308y7xuxSuOOvw:-LaUqX315eCX-zNpc-WK:bcqz9kk) ([raw file](https://github.com/brightec/kbarcode/blob/7c85f9ba9611282f2d81e68b6804a67616032dd8/app/src/main/AndroidManifest.xml#L6)):*
> ```XML
>     package="uk.co.brightec.kbarcode.app">
> 
>

**Review by alistairsykes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/brightec/kbarcode/3)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @NickHolcombe)

___
*[app/src/main/AndroidManifest.xml, line 6 at r2](https://reviewable.io/reviews/brightec/kbarcode/3#-LaUqX308y7xuxSuOOvw:-LaUqx1V1Utkq2JnKQJd:b-896fix) ([raw file](https://github.com/brightec/kbarcode/blob/7c85f9ba9611282f2d81e68b6804a67616032dd8/app/src/main/AndroidManifest.xml#L6)):*
<details><summary><i>Previously, NickHolcombe (Nick) wrote…</i></summary><blockquote>

typo - users :-)
</blockquote></details>

Done.

**Review by NickHolcombe — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/brightec/kbarcode/3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
